import os

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

LOGO_PATH = os.path.join(
    BASE_DIR,
    "assets",
    "logo.webp"
)

os.makedirs("gradecards", exist_ok=True)


def generate_pdf(student, feedback=""):

    filename = f"gradecards/{student['Email']}.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []

    # ==========================
    # LOGO
    # ==========================

    if os.path.exists(LOGO_PATH):

        logo = Image(
            LOGO_PATH,
            width=80,
            height=80
        )

        elements.append(logo)

    # ==========================
    # TITLE
    # ==========================

    elements.append(
        Paragraph(
            "LLOYD INSTITUTE OF ENGINEERING & TECHNOLOGY",
            styles["Title"]
        )
    )

    elements.append(
        Paragraph(
            "GradeAI Performance Report",
            styles["Heading2"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    # ==========================
    # STUDENT DETAILS
    # ==========================

    data = [
        ["Email", student["Email"]],
        ["Quiz 1", str(student["Quiz_1"])],
        ["Quiz 2", str(student["Quiz_2"])],
        ["Quiz 3", str(student["Quiz_3"])],
        ["Total Marks", str(student["Total Marks"])],
        ["Percentage", f"{student['Percentage']:.2f}%"],
        ["Percentile", f"{student['Percentile']:.2f}"],
        ["Rank", str(student["Rank"])],
        ["Grade", student["Grade"]]
    ]

    table = Table(data, colWidths=[150, 250])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 11),
        ])
    )

    elements.append(table)

    elements.append(
        Spacer(1, 20)
    )

    # ==========================
    # REMARKS
    # ==========================

    percentile = student["Percentile"]

    if percentile >= 90:
        remark = "Outstanding Performance"

    elif percentile >= 75:
        remark = "Very Good Performance"

    elif percentile >= 60:
        remark = "Good Performance"

    else:
        remark = "Needs Improvement"

    elements.append(
        Paragraph(
            f"<b>Academic Remark:</b> {remark}",
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1, 15)
    )

    # ==========================
    # AI FEEDBACK
    # ==========================

    if feedback:

        elements.append(
            Paragraph(
                "<b>AI Generated Feedback</b>",
                styles["Heading2"]
            )
        )

        elements.append(
            Paragraph(
                feedback,
                styles["BodyText"]
            )
        )

        elements.append(
            Spacer(1, 15)
        )

    # ==========================
    # FOOTER
    # ==========================

    elements.append(
        Paragraph(
            "Generated by GradeAI",
            styles["Italic"]
        )
    )

    doc.build(elements)

    return filename